# Generated by Django 3.1.6 on 2021-02-14 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripcion')),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('uc', models.IntegerField(blank=True, null=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('nombrebarrio', models.CharField(blank=True, help_text='Ingrese Nombre del Barrio', max_length=50, null=True, unique=True, verbose_name='Nombre del Barrio')),
                ('siglabarrio', models.CharField(blank=True, help_text='Ingrese Sigla del Barrio', max_length=20, null=True, verbose_name='Sigla del Barrio')),
                ('detallebarrio', models.CharField(blank=True, help_text='Ingrese Detalle del Barrio', max_length=255, null=True, verbose_name='Detalle del Barrio')),
            ],
            options={
                'verbose_name_plural': 'Barrios',
            },
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripcion')),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('uc', models.IntegerField(blank=True, null=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('nombredepartamentos', models.CharField(blank=True, help_text='Ingrese su Nombre de Departamento', max_length=50, null=True, unique=True, verbose_name='Departamento')),
                ('sigladepartamentos', models.CharField(blank=True, help_text='Ingrese la Sigla de Departamento', max_length=15, null=True, verbose_name='Sigla del Departamento')),
            ],
            options={
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripcion')),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('uc', models.IntegerField(blank=True, null=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('latitudubicacion', models.CharField(max_length=30, verbose_name='Latitud')),
                ('longitudubicacion', models.CharField(max_length=30, verbose_name='Longitud')),
                ('descripcionubicacion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripcion de la Ubicacion')),
            ],
            options={
                'verbose_name_plural': 'Ubicaciones',
            },
        ),
        migrations.CreateModel(
            name='Provincias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripcion')),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('uc', models.IntegerField(blank=True, null=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('nombreprovincias', models.CharField(blank=True, help_text='Ingrese su Nombre Provincia', max_length=50, null=True, unique=True, verbose_name='Provincia')),
                ('siglaprovincias', models.CharField(blank=True, help_text='Ingrese la Sigla Provincia', max_length=15, null=True, verbose_name='Sigla Provinvia')),
                ('departamentos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geolocalizacion.departamentos')),
            ],
            options={
                'verbose_name_plural': 'Provincias',
            },
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripcion')),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('uc', models.IntegerField(blank=True, null=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('nombremunicipios', models.CharField(blank=True, help_text='Ingrese su Nombre Municipio', max_length=50, null=True, verbose_name='Municipio')),
                ('siglamunicipios', models.CharField(blank=True, help_text='Ingrese la Sigla Municipio', max_length=15, null=True, verbose_name='Sigla Municipio')),
                ('provincias', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geolocalizacion.provincias')),
            ],
            options={
                'verbose_name_plural': 'Municipios',
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripcion')),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('uc', models.IntegerField(blank=True, null=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('nombrelocalidad', models.CharField(blank=True, help_text='Ingrese el Nombre Ciudad Localidad', max_length=50, null=True, verbose_name='Ciudad Localidad')),
                ('municipios', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geolocalizacion.municipios')),
            ],
            options={
                'verbose_name_plural': 'Localidades',
                'ordering': ['-creacion'],
            },
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripcion')),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('uc', models.IntegerField(blank=True, null=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('numerodistrito', models.IntegerField(blank=True, help_text='Ingrese el Numero del Distrito', null=True, verbose_name='Numero del Distrito')),
                ('nombredistrito', models.CharField(blank=True, help_text='Ingrese del Nombre Distrito', max_length=50, null=True, verbose_name='Nombre Distrito')),
                ('sigladistrito', models.CharField(blank=True, help_text='Ingrese la Sigla del Distrito', max_length=10, null=True, verbose_name='Sigla del Distrito')),
                ('localidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geolocalizacion.localidad')),
            ],
            options={
                'verbose_name_plural': 'Distritos',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripcion')),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('uc', models.IntegerField(blank=True, null=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('zonadireccion', models.CharField(blank=True, help_text='Ingrese Nombre de la Zona', max_length=50, null=True, verbose_name='Zona')),
                ('referenciadireccion', models.CharField(blank=True, help_text='Ingrese Referencia', max_length=50, null=True, verbose_name='Referencia')),
                ('viadireccion', models.CharField(blank=True, help_text='Ingrese Nombre de la Via', max_length=50, null=True, verbose_name='Nombre de la Via')),
                ('calledireccion', models.CharField(blank=True, help_text='Ingrese Nombre de la Calle', max_length=50, null=True, verbose_name='Nombre de la Calle')),
                ('numerocasadireccion', models.CharField(blank=True, help_text='Ingrese Numero de Casa', max_length=20, null=True, verbose_name='Numero de Casa')),
                ('avenidadireccion', models.CharField(blank=True, help_text='Ingrese Nombre de la Avenida', max_length=50, null=True, verbose_name='Nombre de la Avenida')),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geolocalizacion.barrio')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geolocalizacion.ubicacion')),
            ],
            options={
                'verbose_name_plural': 'Direccion',
            },
        ),
        migrations.AddField(
            model_name='barrio',
            name='distrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geolocalizacion.distrito'),
        ),
    ]
