# Generated by Django 3.1.6 on 2021-02-15 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recintos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='codigomesa',
            field=models.CharField(help_text='Ingrese Codigo de Mesa', max_length=100, null=True, verbose_name='Codigo de Mesa'),
        ),
    ]
