# Generated by Django 3.1.6 on 2021-02-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recintos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteo',
            name='certificado_img',
            field=models.ImageField(blank=True, null=True, upload_to='certificado/%Y/%m/%d/%h', verbose_name='Imagen de Certificado'),
        ),
    ]
