# Generated by Django 3.1.6 on 2021-02-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recintos', '0002_mesa_codigomesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteo',
            name='marcadopapeleta',
            field=models.IntegerField(default=0, verbose_name='Numero Papeleta Marcados'),
        ),
        migrations.AlterField(
            model_name='conteo',
            name='carnetssobrantes',
            field=models.IntegerField(default=0, verbose_name='Carnet Sobrante'),
        ),
        migrations.AlterField(
            model_name='conteo',
            name='papeletasobreante',
            field=models.IntegerField(default=0, verbose_name='Papeletas Sobrante'),
        ),
        migrations.AlterField(
            model_name='conteo',
            name='total',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total de Votos Partidos'),
        ),
        migrations.AlterField(
            model_name='conteo',
            name='totalpapeletas',
            field=models.IntegerField(default=0, verbose_name='Papeletas o Habilitados'),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='codigomesa',
            field=models.CharField(blank=True, help_text='Ingrese Codigo de Mesa', max_length=100, null=True, verbose_name='Codigo de Mesa'),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='mesahabilitado',
            field=models.IntegerField(default=0, verbose_name='Habilitado en Mesa'),
        ),
        migrations.AlterField(
            model_name='recinto',
            name='recintohabilitado',
            field=models.IntegerField(default=0, verbose_name='Habilitado en Recinto'),
        ),
    ]
