# Generated by Django 3.1.6 on 2021-02-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recintos', '0003_auto_20210215_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conteo',
            name='votovida',
        ),
        migrations.AddField(
            model_name='conteo',
            name='votofpv',
            field=models.IntegerField(default=0, help_text='Frente Para la Victoria', verbose_name='Votos en FPV'),
        ),
    ]
