# Generated by Django 3.1.6 on 2021-02-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recintos', '0004_auto_20210215_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteo',
            name='cerrarpapeleta',
            field=models.IntegerField(default=0, verbose_name='Papeleta Mesa'),
        ),
    ]
