# Generated by Django 3.1.6 on 2021-02-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recintos', '0005_conteo_cerrarpapeleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteo',
            name='certificado_img',
            field=models.ImageField(blank=True, null=True, upload_to='certificado/%Y/%m/%d/', verbose_name='Imagen de Certificado'),
        ),
    ]
