# Generated by Django 3.1.6 on 2021-02-19 03:15

import apps.candidatos.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('militantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripcion')),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('uc', models.IntegerField(blank=True, null=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('titulo', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cargos',
                'ordering': ['-creacion'],
            },
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripcion')),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('uc', models.IntegerField(blank=True, null=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('titulo', models.CharField(blank=True, max_length=250, null=True)),
                ('frase', models.CharField(blank=True, max_length=250, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=apps.candidatos.models.img_url, verbose_name='Imagen de Candidato')),
                ('link_facebook', models.CharField(blank=True, max_length=100, null=True, verbose_name='facebook')),
                ('link_instagram', models.CharField(blank=True, max_length=100, null=True, verbose_name='instagram')),
                ('link_youtube', models.CharField(blank=True, max_length=100, null=True, verbose_name='youtube')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidatos.cargo')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='militantes.persona')),
            ],
            options={
                'verbose_name_plural': 'Candidatos',
                'ordering': ['-creacion'],
            },
        ),
    ]
