# Generated by Django 3.1.6 on 2021-02-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recintos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='mesa',
            field=models.ManyToManyField(blank=True, to='recintos.Mesa'),
        ),
        migrations.AlterField(
            model_name='codigo',
            name='codigopais',
            field=models.CharField(max_length=10, verbose_name='Codigo de Pais'),
        ),
    ]
