# Generated by Django 3.1.6 on 2021-02-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20210221_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='direccion_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
