# Generated by Django 3.1.6 on 2021-02-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recintos', '0001_initial'),
        ('usuarios', '0003_usuario_direccion_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='mesa',
        ),
        migrations.AddField(
            model_name='usuario',
            name='mesas',
            field=models.ManyToManyField(to='recintos.Mesa'),
        ),
    ]
